### ISSUE TITLE
Chicken Jockey should be hostile mob

### ISSUE THREAD

**Issue by Plastikmensch** [Plastikmensch/dynmap-mobs#22]
Currently Chicken Jockeys are counted as passive mobs, but it should be counted as hostile, unless ridden by a Zombified Piglin.
Therefore they are only shown on maps, if the passive mobs layer is enabled.
Also currently there is no distinction between Jockeys.

### To-Do
- [x] Add icon for Zombified Piglin Jockeys
- [x] Add Chicken Jockeys to hostile mobs layer
- [x] Differentiate between Jockeys
